feat(FEC-13362): add new events
kaltura/playkit-js-kava pull request #154
Opened 2023-12-07 13:41 UTC by lianbenjamin

### Description of the Changes

**add new events:**
- enter fullscreen
- exit fullscreen
- info clicked (info)
- download clicked (downloads)
- report clicked (moderation)
- report submitted (moderation)

**dependent on PRs:**
https://github.com/kaltura/playkit-js-info/pull/86
https://github.com/kaltura/playkit-js-downloads/pull/35
https://github.com/kaltura/playkit-js-moderation/pull/67

Solves FEC-13362

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-12-08 11:25 UTC, semarche-kaltura approved these changes

2023-12-08 11:28 UTC, semarche-kaltura commented
@lianbenjamin could you compare bundle size before and after current PR (wanna know if bundle includes only event string from plugins or entire plugins code)

2023-12-10 08:23 UTC, SivanA-Kaltura requested changes

2023-12-10 08:23 UTC, SivanA-Kaltura commented on package.json
> +    "@playkit-js/moderation": "latest",
i know you're replacing it with canary later, but reminder -  always use explicit versions here

2023-12-10 09:39 UTC, lianbenjamin commented
@semarche-kaltura 
after my changes vs before my changes- playkit-kava.js was increased by 2KB and playkit-kava.js.map was increased by 4KB.

2023-12-11 13:25 UTC, merged