feat(FEC-13749): transcript detach analytyc events
kaltura/playkit-js-kava pull request #175
Opened 2024-06-04 14:17 UTC by semarche-kaltura

### Description of the Changes

Add Transcript detach analytic events

resolves: https://kaltura.atlassian.net/browse/FEC-13749

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2024-06-04 17:15 UTC, SivanA-Kaltura requested changes

2024-06-04 17:15 UTC, SivanA-Kaltura commented on src/application-events-model.ts
> +    getEventModel: (payload: any): any => ({
note the error

2024-06-05 10:14 UTC, semarche-kaltura commented on src/application-events-model.ts
> +    getEventModel: (payload: any): any => ({
done

2024-06-05 10:29 UTC, SivanA-Kaltura approved these changes

2024-06-05 10:31 UTC, merged