Captions alignment - Product fix(FEC-14015): analytics | Opacity choose (buttonType :  8) for background & font should send and kava should display buttonValue "1-100%".
kaltura/playkit-js-kava pull request #181
Opened 2024-07-04 11:29 UTC by JonathanTGold

### Description of the Changes

Resolves FEC-14015

2024-07-04 12:05 UTC, semarche-kaltura commented on src/application-events-model.ts
> +      eventVar3: `${String(payload).split(".")[1]}%`
does it possible if payload will be integer, like `10` (without decimal values)?

2024-07-07 09:17 UTC, SivanA-Kaltura requested changes

2024-07-07 09:17 UTC, SivanA-Kaltura commented on demo/plugins.html
> +          ks: 'djJ8MjQyfHPBBV7oyk4Gum-eNT_exa77z-MYwcgwv5aGz4bA5LKz4ODv2EZp9oly1KcMos-xqWueMai87tlPnl6tpXk_CdNoUCSTfklp9MiDz_urIa2pMM6_b1FM7ibLJG2GT931cxN4k_iCBBKpCd9Yp-gss4Lgmra9wASR8aPuLvgp1J2KeUbt
dont use ks in commited code

2024-07-07 09:44 UTC, JonathanTGold commented on demo/plugins.html
> +          ks: 'djJ8MjQyfHPBBV7oyk4Gum-eNT_exa77z-MYwcgwv5aGz4bA5LKz4ODv2EZp9oly1KcMos-xqWueMai87tlPnl6tpXk_CdNoUCSTfklp9MiDz_urIa2pMM6_b1FM7ibLJG2GT931cxN4k_iCBBKpCd9Yp-gss4Lgmra9wASR8aPuLvgp1J2KeUbt
fixed

2024-07-07 09:48 UTC, SivanA-Kaltura approved these changes

2024-07-07 09:48 UTC, merged