feat(FEC-10709, FEC-10712): player visibility - Auto-pause when player is out of view, Autoplay only when player is in view
kaltura/playkit-js-kava pull request #91
Opened 2020-12-23 14:35 UTC by RoyBregman

### Description of the Changes
Tab visibility code was migrated to playkit and KAVA now uses the event dispatched from there

solves FEC-10709, FEC-10712

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2020-12-28 13:25 UTC, yairans reviewed
add tests

2021-01-11 16:44 UTC, OrenMe approved these changes

2021-01-11 16:46 UTC, OrenMe requested changes
please check failing tests

2021-01-12 08:28 UTC, OrenMe approved these changes

2021-01-14 13:56 UTC, merged